### ISSUE TITLE
Errors on signup

### ISSUE THREAD

**Issue by hiteshgarg14** [BuildmLearn/University-Campus-Portal-UCP#11]
1. in case user signup to website and didn't verify email at that time. if after long time if user try to login then he can't login without verifying email address. suppose somehow he deleted that confirmation mail then there is not option to verify again.
2. if user try to signup without filling firstname or lastname fields then email confirmation mail is being sent. which is supposed to show an error.

**Comment by sinwar** [comment]
working on this
