### ISSUE TITLE
Unable to upload profile picture

### ISSUE THREAD

**Issue by mukeshkharita** [BuildmLearn/University-Campus-Portal-UCP#16]
Unable to upload profile picture on /user/edit_profile

**Comment by hiteshgarg14** [comment]
@mukeshkharita  this functionality has not been introduced yet in the code. that's why you can't upload profile picture.

**Comment by pranav15197** [comment]
The functionality to upload a profile picture is already there. If you go to /user/edit_profile/ you can click on the profile picture in order to choose and upload a new picture

**Comment by hiteshgarg14** [comment]
@pranav15197 there is no option to upload a profile picture. Can you paste the screenshot for this one?

**Comment by pranav15197** [comment]
<img width="1280" alt="screen shot 2017-02-25 at 7 23 54 pm" src="https://cloud.githubusercontent.com/assets/4546718/23331646/134508a8-fb90-11e6-9391-96413cc98d6c.png">

If you look at the script added at the end of edit-profile.html, you'll find the code that runs when you click on the profile picture, and that allows you to upload a new one

**Comment by hiteshgarg14** [comment]
Nice. But there is no option or any pop like 'upload photo'. While moving mouse pointer over profile image. Then how will user get to know that there is an hidden option to upload file here?

**Comment by mukeshkharita** [comment]
@pranav15197 There is no option to upload the photo. What user will press to upload the photo?
