### ISSUE TITLE
Can't install ConfigParser module under python3.x environment

### ISSUE THREAD

**Issue by hao555sky** [BuildmLearn/University-Campus-Portal-UCP#17]
Should I use Python2.x? Sorry for if I ask something wrong.

**Comment by ankit-gaur** [comment]
@hao555sky  I used python2(simply python) and everything worked fine.

**Comment by hao555sky** [comment]
OK, I have installed it. And I have recorded the installed issues I met, where should I put it?

**Comment by pranav15197** [comment]
Yes you should be using python 2.x, if you are still facing issues regarding the installation then u can include them here and we can discuss what might be wrong

**Comment by hao555sky** [comment]
Yes， and I know the reason why I can not install, and I have solved other issues when I met, and I want to share it with other beginners. And I met a problem when I register, should I close this issue and open a new issue about the new problem?

**Comment by pranav15197** [comment]
Yes you should open a new issue, and to make sure others don't face the same problems that you met, we can probably add more instructions to the readme file. I am closing this issue now.
