### ISSUE TITLE
Can't add reply on a discussion

### ISSUE THREAD

**Issue by ankit-gaur** [BuildmLearn/University-Campus-Portal-UCP#18]
I have added a user from django-admin and I can post in discussion but I cannot see any option to reply on the discussion thread. I found that reply option is implemented in the api. Is it not implemented in client side code or am I missing something?

**Comment by ankit-gaur** [comment]
Ok, I found out that front end part is incomplete as discussion-list.html doesn't have any link to discussion-detail.html.

**Comment by pranav15197** [comment]
The discussion list, lists the discussion threads, and if you click on the name of any thread, it will take you to the details page of that thread, where you can reply by clicking on the add comment button

**Comment by ankit-gaur** [comment]
ok. Thank you.

**Comment by ankit-gaur** [comment]
@pranav15197 Are you applying for the android app for UCP this time? I know this is not the right place to ask but I couldn't get any contact detail about you? :)

**Comment by pranav15197** [comment]
You can ping me on gmail or hangouts if you want, my email id is pranav15197@gmail.com
