### ISSUE TITLE
ValueError at /user/edit_profile/

### ISSUE THREAD

**Issue by hiteshgarg14** [BuildmLearn/University-Campus-Portal-UCP#5]
On Clicking `save changes` button without filling Age filed. this error occurs :- 

`ValueError at /user/edit_profile/`
`invalid literal for int() with base 10: 'None'`

**Comment by pranav15197** [comment]
The problem should mostly be with the update_profile function in the functions file in login app. We can either add a check their to ensure that the age is an integer.

**Comment by hiteshgarg14** [comment]
@pranav15197 we can handle these errors while writing models or forms or while handling requests in our view functions.

**Comment by hiteshgarg14** [comment]
@pranav15197 the problem here is that age is an empty filed which is not even a number. we can create a form from ModelForm class to avoid this error. as in models.py file age filed is already null=True and Blank=True. django will handle this for us. there is no need of rechecking to ensure that the age is an integer.

**Comment by pranav15197** [comment]
writing a form for validating the incoming data would be a good way. However as the app handles both request through the views and through Rest Apis, I think using serializers would be a better way to validate the data. If you look into the serializers file in each app there are plenty of serializer files which do this. We can add one for the edit profile part as well.

**Comment by hiteshgarg14** [comment]
@pranav15197  can you please guide me through any serializers.py file in project structure which validate data for errors.
